
all: exercise2.pdf exercise3.pdf exercise4.pdf

exercise2.pdf: exercise2.tex
	miktex-pdflatex exercise2.tex

exercise3.pdf: exercise3.tex
	miktex-pdflatex exercise3.tex

exercise4.pdf: exercise4.tex
	miktex-pdflatex exercise4.tex

.PHONY:
clean:
	rm *.log *.aux
