/* DSblock model generated by Dymola from Modelica model TwoTanks.TwoTanks_basic
 Dymola Version 2016 FD01 (64-bit), 2015-10-13 translated this at Fri Jan 19 17:11:20 2018

   */

#include <matrixop.h>
/* Declaration of C-structs */
/* Prototypes for functions used in model */
/* Codes used in model */
/* DSblock C-code: */

#define NX_    2
#define NX2_   0
#define NU_    0
#define NY_    0
#define NW_    5
#define NP_    6
#define NPS_   0
#define MAXAuxStr_   0
#define MAXAuxStrLen_   500
#define NHash1_ -1773487839
#define NHash2_ -1988903805
#define NHash3_ 0
#define NI_    0
#define NRelF_ 0
#define NRel_  0
#define NTim_  0
#define NSamp_ 0
#define NCons_ 0
#define NA_    0
#define SizePre_ 0
#define SizeEq_ 2
#define SizeDelay_ 0
#define QNLmax_ 0
#define MAXAux 0
#define NrDymolaTimers_ 0
#define NWhen_ 0
#define NCheckIf_ 0
#define NGlobalHelp_ 0
#define NGlobalHelpI_ 0
#ifndef NExternalObject_
#define NExternalObject_ 0
#endif
#include <moutil.c>
PreNonAliasDef(0)
PreNonAliasDef(1)
PreNonAliasDef(2)
PreNonAliasDef(3)
PreNonAliasDef(4)
PreNonAliasDef(5)
#if !defined(DYM2CCUR)
 DYMOLA_STATIC const char*modelName="TwoTanks.TwoTanks_basic";
#endif
DYMOLA_STATIC const char*usedLibraries[]={0};
DYMOLA_STATIC const char*dllLibraryPath[]={0};
DYMOLA_STATIC const char*default_dymosim_license_filename=
 "/home/rendell/.dynasim/dymola.lic";
#include <dsblock1.c>

/* Define variable names. */

#define Sections_

TranslatedEquations

InitialSection
#if defined(DynSimStruct) || defined(BUILDFMU)
DYNX(W_,0) = 3.14;
DYNX(W_,1) = 9.81;
#endif
BoundParameterSection
InitialSection
InitialSection
InitialStartSection
InitialSection
DefaultSection
InitializeData(0)
InitialSection
InitialSection2
DYNX(X_,1) = 2.0;
DYNX(X_,0) = 4.0;
InitialSection2
Init_=false;InitializeData(2);Init_=true;
EndInitialSection

OutputSection

DynamicsSection
DYNX(W_,2) = 9.81*DYNX(DP_,4)*DYNX(X_,0);
DYNX(W_,3) = 9.81*DYNX(DP_,4)*DYNX(X_,1);
DYNX(W_,4) = divmacro(3.14*(DYNX(W_,2)-DYNX(W_,3))*powmacro(DYNX(DP_,3),"D",4,
  "4"),"3.14*((p1-p2)*D^4)",128.0*DYNX(DP_,5)*DYNX(DP_,2),"128.0*(mu*L)");
 /* Linear system of equations to solve. */
DYNX(F_,1) = RememberSimple_(DYNX(F_,1), 0);
SolveScalarLinearParametric(DYNX(DP_,1),"A2", DYNX(W_,4),"q", DYNX(F_,1),
  "der(h2)");
 /* End of Equation Block */ 

 /* Linear system of equations to solve. */
DYNX(F_,0) = RememberSimple_(DYNX(F_,0), 1);
SolveScalarLinearParametric(DYNX(DP_,0),"A1",  -DYNX(W_,4)," -q", DYNX(F_,0),
  "der(h1)");
 /* End of Equation Block */ 


AcceptedSection1

AcceptedSection2

DefaultSection
InitializeData(1)
EndTranslatedEquations

#include <dsblock6.c>

PreNonAliasNew(0)
StartNonAlias(0)
DeclareVariable("pi", "", 3.14, 0.0,0.0,0.0,0,513)
DeclareVariable("g", "", 9.81, 0.0,0.0,0.0,0,513)
DeclareParameter("A1", "Area of tank 1", 0, 1.0, 0.0,0.0,0.0,0,560)
DeclareParameter("A2", "Area of tank 2", 1, 2.0, 0.0,0.0,0.0,0,560)
DeclareParameter("L", "Pipe length", 2, 0.1, 0.0,0.0,0.0,0,560)
DeclareParameter("D", "Pipe diameter", 3, 0.2, 0.0,0.0,0.0,0,560)
DeclareParameter("rho", "Fluid density", 4, 0.2, 0.0,0.0,0.0,0,560)
DeclareParameter("mu", "Fluid dynamic viscosity", 5, 0.002, 0.0,0.0,0.0,0,560)
DeclareVariable("p1", "Pressure in tank 1", 0.0, 0.0,0.0,0.0,0,512)
DeclareVariable("p2", "Pressure in tank 2", 0.0, 0.0,0.0,0.0,0,512)
DeclareState("h1", "Liquid level in tank 1", 0, 0.0, 0.0,0.0,0.0,0,544)
DeclareDerivative("der(h1)", "der(Liquid level in tank 1)", 0.0, 0.0,0.0,0.0,0,512)
DeclareState("h2", "Liquid level in tank 2", 1, 0.0, 0.0,0.0,0.0,0,544)
DeclareDerivative("der(h2)", "der(Liquid level in tank 2)", 0.0, 0.0,0.0,0.0,0,512)
DeclareVariable("q", "Volume flow rate between tanks", 0.0, 0.0,0.0,0.0,0,512)
EndNonAlias(0)

#define DymolaHaveUpdateInitVars 1
#include <dsblock5.c>

DYMOLA_STATIC void UpdateInitVars(double*time, double* X_, double* XD_, double* U_, double* DP_, int IP_[], Dymola_bool LP_[], double* F_, double* Y_, double* W_, double QZ_[], double duser_[], int iuser_[], void*cuser_[],struct DYNInstanceData*did_) {
static Real initStore[1];
}
StartDataBlock
StartEqBlock
DoRemember_(DYNX(F_,0), 0.0, 1);
DoRemember_(DYNX(F_,1), 0.0, 0);
EndEqBlock
EndDataBlock
